### ISSUE TITLE
Great Work! Expecting release to run the Structure Recognition

### ISSUE THREAD

**Issue by prasad01dalavi** [muhd-umer/MS-TDaTSR#16]
Hello Team,

When can we expect full working structure recognition module?

**Comment by muhd-umer** [comment]
Hi @prasad01dalavi,

While we can't give you any definite date as to when our Table Structure Recognition pipeline finalizes, you could [watch this repo](https://github.com/user/repository/subscription) to stay updated with our future releases.<br/> With that said, we are still in our planning phase and an **estimated two/three months** may be taken to conclude TSR.

**Comment by muhd-umer** [comment]
Q: Answered.
